=== alakim/grains/trunk/dwin/buglist/defs/buglist.xsd
<?xml version="1.0" encoding="UTF-8"?>
<!-- edited with XML Spy v4.3 U (http://www.xmlspy.com) by alakim (IVC) -->
<!--W3C Schema generated by XML Spy v4.3 U (http://www.xmlspy.com)-->
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">
	<xs:element name="application" type="xs:string">
		<xs:annotation>
			<xs:documentation>Описание приложения, для котогоро составляется баглист</xs:documentation>
		</xs:annotation>
	</xs:element>
	<xs:element name="bug">
		<xs:annotation>
			<xs:documentation>Ошибка</xs:documentation>
		</xs:annotation>
		<xs:complexType mixed="true">
			<xs:choice minOccurs="0" maxOccurs="unbounded">
				<xs:element ref="ref"/>
				<xs:element ref="fixed"/>
				<xs:element ref="p"/>
				<xs:element ref="supposition"/>
				<xs:element ref="statement"/>
				<xs:element ref="todo"/>
			</xs:choice>
			<xs:attribute name="id" type="xs:ID" use="required">
				<xs:annotation>
					<xs:documentation>Идентификатор</xs:documentation>
				</xs:annotation>
			</xs:attribute>
			<xs:attribute name="date" type="xs:date" use="required">
				<xs:annotation>
					<xs:documentation>Дата обнаружения ошибки</xs:documentation>
				</xs:annotation>
			</xs:attribute>
			<xs:attribute name="tester" type="xs:IDREF" use="required">
				<xs:annotation>
					<xs:documentation>Тестер, обнаруживший ошибку</xs:documentation>
				</xs:annotation>
			</xs:attribute>
			<xs:attribute name="title" type="xs:string" use="required">
				<xs:annotation>
					<xs:documentation>Заголовок - краткое наименование ошибки.</xs:documentation>
				</xs:annotation>
			</xs:attribute>
			<xs:attribute name="module" type="xs:IDREF" use="required">
				<xs:annotation>
					<xs:documentation>Ссылка на программный модуль, в котором произошла ошибка</xs:documentation>
				</xs:annotation>
			</xs:attribute>
			<xs:attribute name="priority" type="xs:int">
				<xs:annotation>
					<xs:documentation>Приоритет исправления ошибки</xs:documentation>
				</xs:annotation>
			</xs:attribute>
		</xs:complexType>
	</xs:element>
	<xs:element name="buglist">
		<xs:annotation>
			<xs:documentation>Корневой элемент. Содержит список ошибок и дополнительные словари.</xs:documentation>
		</xs:annotation>
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="application"/>
				<xs:element ref="persons"/>
				<xs:element ref="categories"/>
				<xs:element ref="modules"/>
				<xs:element ref="bugs"/>
			</xs:sequence>
			<xs:attribute name="bugPrefix" type="xs:string" use="optional">
				<xs:annotation>
					<xs:documentation>Префикс, добавляемый к идентификатору ошибки.</xs:documentation>
				</xs:annotation>
			</xs:attribute>
			<xs:attribute name="comments" type="xs:string" use="optional">
				<xs:annotation>
					<xs:documentation>Комментарии к баглисту</xs:documentation>
				</xs:annotation>
			</xs:attribute>
		</xs:complexType>
	</xs:element>
	<xs:element name="bugs">
		<xs:annotation>
			<xs:documentation>Коллекция ошибок</xs:documentation>
		</xs:annotation>
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="bug" maxOccurs="unbounded"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="categories">
		<xs:annotation>
			<xs:documentation>Список категорий для классификации ошибок</xs:documentation>
		</xs:annotation>
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="category" maxOccurs="unbounded"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="category">
		<xs:annotation>
			<xs:documentation>Категория для классификации ошибок</xs:documentation>
		</xs:annotation>
		<xs:complexType>
			<xs:simpleContent>
				<xs:extension base="xs:string">
					<xs:attribute name="id" type="xs:ID" use="required">
						<xs:annotation>
							<xs:documentation>Идентификатор</xs:documentation>
						</xs:annotation>
					</xs:attribute>
				</xs:extension>
			</xs:simpleContent>
		</xs:complexType>
	</xs:element>
	<xs:element name="module">
		<xs:annotation>
			<xs:documentation>Описание программного модуля</xs:documentation>
		</xs:annotation>
		<xs:complexType>
			<xs:simpleContent>
				<xs:extension base="xs:string">
					<xs:attribute name="id" type="xs:ID" use="required">
						<xs:annotation>
							<xs:documentation>Идентификатор</xs:documentation>
						</xs:annotation>
					</xs:attribute>
				</xs:extension>
			</xs:simpleContent>
		</xs:complexType>
	</xs:element>
	<xs:element name="modules">
		<xs:annotation>
			<xs:documentation>Коллекция описаний программных модулей</xs:documentation>
		</xs:annotation>
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="module" maxOccurs="unbounded"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="person">
		<xs:annotation>
			<xs:documentation>Персональные данные участника проекта</xs:documentation>
		</xs:annotation>
		<xs:complexType>
			<xs:simpleContent>
				<xs:extension base="xs:string">
					<xs:attribute name="id" type="xs:ID" use="required">
						<xs:annotation>
							<xs:documentation>Идентификатор</xs:documentation>
						</xs:annotation>
					</xs:attribute>
				</xs:extension>
			</xs:simpleContent>
		</xs:complexType>
	</xs:element>
	<xs:element name="persons">
		<xs:annotation>
			<xs:documentation>Коллекция персональных данных участников проекта</xs:documentation>
		</xs:annotation>
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="person" maxOccurs="unbounded"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="ref">
		<xs:annotation>
			<xs:documentation>Ссылка на элемент документа</xs:documentation>
		</xs:annotation>
		<xs:complexType>
			<xs:attribute name="category" type="xs:IDREF" use="optional">
				<xs:annotation>
					<xs:documentation>Ссылка на элемент "Категория"</xs:documentation>
				</xs:annotation>
			</xs:attribute>
			<xs:attribute name="bug" type="xs:IDREF" use="optional"/>
		</xs:complexType>
	</xs:element>
	<xs:element name="fixed">
		<xs:annotation>
			<xs:documentation>Отметка об устранении ошибки</xs:documentation>
		</xs:annotation>
		<xs:complexType mixed="true">
			<xs:attribute name="date" type="xs:date" use="required">
				<xs:annotation>
					<xs:documentation>Дата устранения ошибки</xs:documentation>
				</xs:annotation>
			</xs:attribute>
			<xs:attribute name="programmer" type="xs:IDREF" use="required">
				<xs:annotation>
					<xs:documentation>Программист, устранивший ошибку</xs:documentation>
				</xs:annotation>
			</xs:attribute>
		</xs:complexType>
	</xs:element>
	<xs:element name="p">
		<xs:annotation>
			<xs:documentation>Абзац текста</xs:documentation>
		</xs:annotation>
		<xs:complexType mixed="true"/>
	</xs:element>
	<xs:element name="supposition">
		<xs:annotation>
			<xs:documentation>Предположение о причине ошибки</xs:documentation>
		</xs:annotation>
		<xs:complexType mixed="true">
			<xs:choice minOccurs="0" maxOccurs="unbounded">
				<xs:element ref="ref"/>
			</xs:choice>
		</xs:complexType>
	</xs:element>
	<xs:element name="statement">
		<xs:annotation>
			<xs:documentation>Утверждение о причине ошибки</xs:documentation>
		</xs:annotation>
		<xs:complexType mixed="true">
			<xs:choice minOccurs="0" maxOccurs="unbounded">
				<xs:element ref="ref"/>
			</xs:choice>
		</xs:complexType>
	</xs:element>
	<xs:element name="todo">
		<xs:annotation>
			<xs:documentation>Предполагаемое действие</xs:documentation>
		</xs:annotation>
		<xs:complexType mixed="true">
			<xs:choice minOccurs="0" maxOccurs="unbounded">
				<xs:element ref="ref"/>
			</xs:choice>
		</xs:complexType>
	</xs:element>
</xs:schema>

=== alakim/grains/dwin/buglist/buglist.xml
<?xml version="1.0" encoding="Windows-1251"?>
<?xml-stylesheet type="text/xsl" href="defs/buglist.xslt" ?>
<buglist bugPrefix="sa" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="defs/buglist.xsd">
	<application>Модуль DWL</application>
	<persons>
		<person id="alakim">Акимов А.В.</person>
		<person id="NA">Андрущенко Н.</person>
	</persons>
	<categories>
		<category id="cat_Usability">Удобство использования</category>
		<category id="cat_Bug">Ошибка</category>
	</categories>
	<modules>
		<module id="dwl">DWL</module>
		<module id="PhotoBox">PhotoBox</module>
	</modules>
	<bugs>
		<bug id="b1" date="2008-10-23" title="Некорректный рендеринг в IE (глюк №2)" module="PhotoBox" tester="NA">
			<p>В переписке именуется "глюк №2".</p>
			<p>Задал в скрипте ширину окна по размеру изображения.
Вызываю свой HTML-файл (или нажимаю кнопку "Обновить" в браузере).
В IE 6.0 окно с изображением откроется несколько шире изображения (справа будет белая вертикальная полоса).
Закроем окно с изображением и снова щелкнем по превьюшке. Теперь окно открывается точно по размеру изображения. И будет всё время открываться точно по размеру, пока не нажмем на кнопку "Обновить" в браузере. После этого картина повторится.
В FF 2.0.0.9 сразу же всё нормально. </p>
			<fixed date="2008-10-26" programmer="alakim"/>
		</bug>
		<bug id="b2" date="2008-10-23" title="Некорректные размеры окна в IE" module="dwl" tester="NA">
			<p>для IE приходится высоту окна увеличивать на 5 пикс. относительно высоты картинки (а для FF и Оперы - не надо).</p>
		</bug>
		<bug id="b3" date="2008-10-23" title="Некорректное формирование заголовка окна при большой длине строки заголовка" module="dwl" tester="NA">
			<p>Еще наткнулся на небольшую недоделку.
Пощелкайте, напр., здесь по фотографиям:
http://orthonord.ru/genealogy/syren/arhim_alexij/
Если текст в заголовке очень длинный и не помещается в одну строку, то он переносится. Такого подарка я даже не ожидал.
Но!
При этом ширина строки определяется по полной ширине заголовка, вместе с кнопками сворачивания и закрытия окна. В результате текст в некоторых случаях оказывается под этими кнопками.</p>
			<fixed date="2008-10-26" programmer="alakim"/>
		</bug>
		<bug date="2008-10-27" id="b4" title="Открытие нескольких независимых окон" module="dwl" tester="NA">
			<ref category="cat_Usability"/>
			<p>Хотелось бы так, чтобы "по умолчанию" всё открывалось в одном окне, но чтобы юзер имел возможность, если хочет, открыть в другом окне. Теперь "по умолчанию" каждое изображение открывается в отдельном окне. Мне кажется, это менее удобно, потому что для юзера добавляется лишняя операция по закрытию окна, и это его быстро начнет раздражать. Мне как раз нравилось, что всё открывалось в одном окне. </p>
			<p>Но вот как сделать, чтобы у юзера появился такой выбор - не могу понять. Я не вижу среди событий Ява-скриптов ни одного, которое можно было бы использовать для организации такой альтернативы. Напр., удобно было бы организовать через двойной клик, или через клик с какой-нибудь клавиатурной клавишей (напр., Ctrl). Но в документации в списке событий - единственный onclick... </p>
			<fixed date="2008-10-29" programmer="alakim">реализована возможность добавления pin-кнопок</fixed>
		</bug>
		<bug date="2008-10-27" id="b5" title="Теги разметки в заголовках окна" module="dwl" tester="NA">
			<ref category="cat_Usability"/>
			<p>Нельзя ли сделать, чтобы в заголовке окна воспринимался тэг курсива?</p>
			<statement>Ничего здесь делать не надо. Просто в строку заголовка включаются соответствующие HTML-теги, и все работает.</statement>
			<fixed date="2008-10-28" programmer="alakim">оно и так все работало</fixed>
		</bug>
		<bug date="2008-10-27" id="b6" title="Некорректное отображение индикатора загрузки" module="PhotoBox" tester="NA">
			<ref category="cat_Bug"/>
			<p>Индикатор загрузки отображается очень короткое время, после чего появляется пустое окно, размеры которого соответствуют размерам изображения. Окно остается пустым до тех пор, пока изображение не загрузится полностью.</p>
			<fixed date="2008-10-28" programmer="alakim"/>
		</bug>
		<bug date="2008-10-29" id="b7" title="Некорректное отображение всплывающей подсказки" module="PhotoBox" tester="NA">
			<p>Оказалось, что в DWL вместо параметра "alt" всё время используется параметр "title".</p>
			<fixed date="2008-10-29" programmer="alakim"/>
		</bug>
		<bug date="2008-10-29" id="b8" title="Предварительная загрузка пиктограмм" module="dwl" tester="NA">
			<ref category="cat_Usability"/>
			<p>Загружать служебную графику (кнопки, прогресс-бар) заранее.</p>
			<fixed date="2008-10-30" programmer="alakim"/>
		</bug>
		<bug date="2008-10-29" id="b9" title="Начальный размер окна" module="PhotoBox" tester="NA">
			<ref category="cat_Usability"/>
			<p>Начальный размер окна должен быть установлен по размеру прогресс-бара. Чтобы красиво было.</p>
			<fixed date="2008-10-30" programmer="alakim"/>
		</bug>
		<bug date="2008-10-31" id="b10" title="Ошибки предварительной загрузки служебной графики" module="dwl" tester="NA">
			<p>Вот что показала отладка под Fiddler'ом с промежуточной очисткой кэша.</p>
			<p>В процессе загрузки HTML-страницы загружается и выполнятся dwlite.js. При этом скрипт пытается загрузить графику со своими кнопками. Но загрузка каждой из них завершается 404-й ошибкой. Что и следовало ожидать - графика ведь загружается невесть откуда... При этом сервер передает вполне реальные кб - очевидно, с текстом, соответствующим описанию 404-й ошибки.</p>
			<p>Затем загружается и выполнятся PhotoBox.js. Он (в моем случае) переопределяет DWL.$includePath. Но уже поздно - попытка загрузить графику уже закончилась и снова не повторяется.</p>
			<p>Затем я щелкаю по своей фотографии. Открывается окно под размер прогресс-бара, и прогресс-бар успешно показывается. Картинка загружается. Но! На месте трех кнопок в заголовке окна видны пустые квадратики. И только после завершения загрузки основного изображения начинают загружаться картинки для кнопок - из переопределенного места includePath.</p>
			<p>Выход пока я нашел только один - в dwlite.js в 84-й строке прописать: «includePath: "/dwin",»...		</p>
			<fixed date="2008-11-03" programmer="alakim"/>
		</bug>
		<bug date="2008-10-31" id="b11" title="Рецидив ошибки b3" module="dwl" tester="NA">
			<ref bug="b3"/>
			<p>...В этом же релизе добавлена возможность "пришпилить" окно, чтобы оно не закрывалось при открытии нового окна.</p>
			<p>А Вы не забыли после этого отъюстировать размер поля под текст заголовка? Сейчас встретился несколько раз со случаями, когда текст заголовка "подлезает" под эту кнопку.</p>
			<fixed date="2008-11-03" programmer="alakim"/>
		</bug>
		<bug date="2008-11-05" id="b12" title="Ошибка отображения тела диалога в IE" module="dwl" tester="alakim">
			<p>При отображении в IE6 тело диалога оказывается уже, чем надо. Справа образуется отступ, равный по ширине суммарной длине кнопок, размещаемых в заголовке.</p>
			<fixed date="2008-11-05" programmer="alakim"/>
		</bug>
		<bug date="2008-11-10" id="b13" title="Бесконечное ожидание загрузки фотографии" module="PhotoBox" tester="NA">
			<p>У меня была ссылка на несуществующую фотографию. И, похоже, при ее открытии скрипт вошел в бесконечный цикл ожидания.</p>
			<p>Нужно установить таймаут на ожидание загрузки.</p>
			<fixed date="2008-11-11" programmer="alakim"/>
		</bug>
		<bug date="2008-11-11" id="b14" title="Некорректная верстка заголовка и тела диалога в IE6" module="dwl" tester="NA">
			<ref bug="b12"/>
			<p>Видимо, в результате исправления глюка b12  возобновился глюк залезания текста заголовка под кнопки.</p>
			<fixed date="2008-11-25" programmer="alakim"/>
		</bug>
		<bug date="2008-11-14" id="b15" title="Попытка превышения максимальной высоты окна" module="PhotoBox" tester="NA">
			<ref category="cat_Usability"/>
			<p>Фотографии с выше, чем задано параметром maxHeight в PhotoBox.js. По нашей с Вами задумке справа должна появиться полоса вертикальной прокрутки. Но она не появляется.
Причем в FF и Опере вместо нее появляется вертикальная белая полоса. А в IE6 ничего не появляется.</p>
			<statement>Дело в том, что в модуле PhotoBox при открытии диалога скроллинг запрещен. Это делается для того, чтобы улучшить отображение в IE. Если скроллинг разрешить, то в IE почему-то появляется белая полоса справа.</statement>
			<fixed date="2008-11-25" programmer="alakim"/>
		</bug>
	</bugs>
</buglist>
