=== alakim/grains/trunk/tools/jsDocTests/manual/xdefs/manual.dtd
<!ENTITY % basicmarkup_cont "#PCDATA | ref | img | class | sel | code | file | nobr">
<!ENTITY % basicmarkup "(%basicmarkup_cont;)*">
<!ENTITY % somecontent "p | code | file | cmd | list | picture | table | objTable | cit | note | srctext | notice | attention | conclusion | definition">
<!ENTITY dash "&#8211;">
<!ENTITY arrowright "&#8594;">
<!ENTITY arrowleft "&#8592;">
<!-- статья - корневой элемент -->
<!ELEMENT article (section, book*)>
<!-- раздел документа 
	id - идентификатор
	title - заголовок 
	viewmode - вид отображения
		normal - традиционный
		table - все подразделы сводятся в таблицу-->
<!ELEMENT section (section | thesis | optional | %somecontent;)*>
<!ATTLIST section
	id ID #IMPLIED
	title CDATA #REQUIRED
	viewmode (normal | table) "normal"
	displayInTOC (yes | no) "yes"
>
<!-- абзац текста -->
<!ELEMENT p %basicmarkup;>
<!-- список 
	marker - вид маркера-->
<!ELEMENT list (caption?, li+)>
<!ATTLIST list
	marker (bullet | num | none) "bullet"
>
<!-- заголовок списка -->
<!ELEMENT caption %basicmarkup;>
<!-- элемент списка
	name - имя элемента (например, если это список переменны, то это имя переменной -->
<!ELEMENT li (%basicmarkup_cont; | list | notice | optional | note)*>
<!ATTLIST li
	name CDATA #IMPLIED
>
<!-- иллюстрация 
		src - ссылка на файл
		текст - подпись к рисунку-->
<!ELEMENT picture (#PCDATA)>
<!ATTLIST picture
	src CDATA #REQUIRED
>
<!--in-line image
		src - ссылка на файл-->
<!ELEMENT img EMPTY>
<!ATTLIST img
	src CDATA #REQUIRED
>
<!-- теги таблицы -->
<!ELEMENT table (tr)+>
<!ATTLIST table
	border CDATA #IMPLIED
>
<!ELEMENT tr (td | th)+>
<!ATTLIST tr
	class CDATA #IMPLIED
>
<!ELEMENT th %basicmarkup;>
<!ATTLIST th
	rowspan CDATA #IMPLIED
	colspan CDATA #IMPLIED
>
<!ELEMENT td %basicmarkup;>
<!ATTLIST td
	rowspan CDATA #IMPLIED
	colspan CDATA #IMPLIED
>
<!-- гиперссылка 
	sect - ссылка на главу
	url - URL источника
	xart - ссылка на внешний файл, отвечающий article.dtd. 
			После имени файла через знак # можно указать идентификатор целевой секции
	xSoftClass - ссылка на внешний файл, отвечающий XSoftDoc/class.dtd
	-->
<!ELEMENT ref (#PCDATA)>
<!ATTLIST ref
	sect IDREF #IMPLIED
	url CDATA #IMPLIED
	xart CDATA #IMPLIED
	book IDREF #IMPLIED
	xSoftClass CDATA #IMPLIED
>
<!--неразрывный текст-->
<!ELEMENT nobr (#PCDATA)>
<!--пример программного кода
	если родительский элемент - p, то отображается inline
	в противном случае - в виде блока
-->
<!ELEMENT code (#PCDATA | sel | optional | cs_region)*>
<!-- имя файла, или некоторый путь
-->
<!ELEMENT file (#PCDATA)>
<!--пример работы с командной строкой
-->
<!-- регион кода программы на C# -->
<!ELEMENT cs_region (#PCDATA | cs_region)*>
<!ATTLIST cs_region
	name CDATA #IMPLIED
	display (none | block) "none"
>
<!ELEMENT cmd (#PCDATA | sel)*>
<!-- тезис 
	dsc - описание-->
<!ELEMENT thesis (%somecontent;)*>
<!ATTLIST thesis
	dsc CDATA #REQUIRED
>
<!-- цитата - для читателя-->
<!ELEMENT cit %basicmarkup;>
<!--заметка не для читателя -->
<!ELEMENT note %basicmarkup;>
<!-- текст из первоисточника - не для читателя -->
<!ELEMENT srctext %basicmarkup;>
<!-- имя класса -->
<!ELEMENT class (#PCDATA)>
<!-- выделенный текст -->
<!ELEMENT sel ANY>
<!-- примечание для читателя -->
<!ELEMENT notice %basicmarkup;>
<!-- особо важное примечание для читателя -->
<!ELEMENT attention %basicmarkup;>
<!-- определение некоторого понятия 
	term - понятие (не отображается, а служит для ссылок)
-->
<!ELEMENT definition %basicmarkup;>
<!ATTLIST definition
	term CDATA #REQUIRED
>
<!-- таблица, наполняемая из произвольных тегов - объектов
каждый такой тег преобразуется в строку таблицы 
	width - ширина таблицы-->
<!ELEMENT objTable (tblColumn+, tblObjects)>
<!ATTLIST objTable
	width CDATA #IMPLIED
>
<!-- определение колонки для таблицы 
	select - имя атрибута (символ "@" не ставится), из которого следует выбирать значение. 
		Если вместо имени атрибута стоит точка, то выводится содержимое тега
		Если вместо имени атрибута стоит #, то выводится номер записи
	style - описание стиля CSS для ячеек данной колонки
	текст - заголовок колонки (если во всех колонках этот текст пустой, то строка заголовков 
				не отображается)-->
<!ELEMENT tblColumn (#PCDATA)>
<!ATTLIST tblColumn
	select CDATA #REQUIRED
	style CDATA #IMPLIED
	align (center | left | right) "left"
	valign (center | top | bottom) "top"
>
<!-- объекты - содержимое таблицы -->
<!ELEMENT tblObjects ANY>
<!ELEMENT book (#PCDATA | ref)*>
<!ATTLIST book
	id ID #REQUIRED
>
<!-- необязательный фрагмент
       обычно скрыт, но при желании можно показать -->
<!ELEMENT optional (%basicmarkup_cont; | caption | notice | attention | cmd | p)*>
<!ELEMENT conclusion (#PCDATA)>

=== alakim/grains/trunk/tools/jsDocTests/manual/manual.xml
<?xml version="1.0" encoding="UTF-8"?>
<!-- edited with XML Spy v4.3 U (http://www.xmlspy.com) by alakim (IVC) -->
<!DOCTYPE article SYSTEM "xdefs/manual.dtd">
<?xml-stylesheet type="text/xsl" href="xdefs/manual.xslt"?>
<article>
	<section title="Модуль jsDoc">
		<section title="Общее описание">
			<p>Предназначен для создания страниц документации скриптовых модулей.</p>
			<p>Документация оформляется в виде вызова конструктора <code>new Documentation</code>. Аргументами конструктора являются: имя документируемого объекта, его описание, и структура данных, описывающае его атрибуты и методы.</p>
			<p>Отображение документации производится вызовом статического метода <code>Documentation.show()</code>, добавляющего сформированную документацию в конец существующей веб-страницы.</p>
		</section>
		<section title="Формат данных для описания атрибутов и методов объекта">
			<p>Структура данных представляет собой массив, содержащий описания атрибутов и методов. Каждое такое описание представяет собой структуру, содержащую следующие атрибуты:</p>
			<list>
				<li name="type">тип элемента: <code>attribute</code>, <code>method</code>, <code>object</code>, <code>class</code>, <code>property</code>, и т.п.</li>
				<li name="name">имя элемента</li>
				<li name="dsc">описание элемента</li>
				<li name="children">(для элементов типа <code>object</code>) - массив, содержащий описания атрибутов и методов данного объекта</li>
			</list>
			<notice>Если описанный атрибут или метод отсутствует в объекте, его описание обозначается серым цветом шрифта.</notice>
			<p>Если документируемый объект является <sel>конструктором класса</sel>, то для описания <sel>нестатических членов</sel> данного класса следует создать атрибут типа <code>object</code> с именем <code>prototype</code>, и в коллекции <code>children</code> этого атрибута описать нестатические члены класса. При этом тип объекта для данного конструктора обозначается <code>class</code>.</p>
			<p>Если <sel>нестатические члены</sel> класса формируются <sel>не в прототипе</sel>, а в конструкторе, или добавляются в процессе выполнения кода, то для их описания добавляется атрибут типа <code>instance</code>, и в коллекции <code>children</code> этого атрибута добавляются описания данных членов класса.</p>
		</section>
	</section>
</article>
